apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: igfurlan/gitops
  newTag: 52b35a82b1ea6814128e5c0c6228690166cf6c8f
